### ISSUE TITLE
Provide a way for adding icons by class 

### ISSUE THREAD

**Issue by nikitul** [jonataswalker/ol3-contextmenu#25]
Hello there. 
I must say that I love your plugin.

I want to know if it is possible to create my own icon classes (similar with ol-ctx-menu-zoom-in), or some based on font icons (like fontawsome ) and use them with  contextmenu . For now it is possible to add icons only by providing an url .
And using classes makes it easier to integrate with other frameworks (like bootstrap, foundation).

The current way of adding icons have a bug because for each right mouse click, a new "ol-ctx-menu-icon" class is inserted in the < li > class list only for the item with a custom icon. 
I accidentally observed it.

Have a nice day :)

**Comment by jonataswalker** [comment]
Hey @nikitul,

Actually it's already possible what you want, I'll update the docs. For instance you can:
```css
.marker {
  text-indent: 20px;
  background-size: 20px auto;
  background-image: url("img/marker.png");
  background-repeat: no-repeat;
  background-position: left center;
}
```

And pass a `classname` property to an item:
```javascript
  var contextmenu_items = [
    {
      text: 'Add a Marker',
      classname: 'marker', // good to go
      // icon: 'img/marker.png', // can get rid of this
      callback: marker
    }
  ];
```
